# Generated by Django 5.2.14 on 2026-05-07 21:21

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vector_store', '0001_enable_pgvector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(choices=[('text', 'Plain text'), ('file', 'Uploaded file'), ('web', 'Web page')], default='text', max_length=16)),
                ('source_uri', models.CharField(blank=True, max_length=2048)),
                ('raw_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vector_document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='vector_store.document')),
            ],
            options={
                'db_table': 'vector_chunk',
                'ordering': ['document', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', '-created_at'], name='vector_docu_owner_i_05e96b_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chunk',
            constraint=models.UniqueConstraint(fields=('document', 'position'), name='uniq_chunk_position_per_doc'),
        ),
    ]
