# Generated by Django 5.2.14 on 2026-05-07 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('semantic', 'Semantic'), ('web', 'Web')], db_index=True, default='semantic', max_length=16)),
                ('query', models.CharField(max_length=512)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search query',
                'verbose_name_plural': 'Search queries',
                'db_table': 'queries_searchquery',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='queries_sea_user_id_5c595a_idx'), models.Index(fields=['user', 'kind', '-created_at'], name='queries_sea_user_id_ca316f_idx')],
            },
        ),
    ]
