# Generated by Django 5.2.14 on 2026-05-08 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planning', 'Planning'), ('searching', 'Searching'), ('fetching', 'Fetching'), ('retrieving', 'Retrieving'), ('synthesizing', 'Synthesizing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('document_ids', models.JSONField(blank=True, default=list)),
                ('report_text', models.TextField(blank=True)),
                ('report_sources', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research session',
                'verbose_name_plural': 'Research sessions',
                'db_table': 'research_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='research_se_user_id_60aa34_idx'), models.Index(fields=['user', 'status'], name='research_se_user_id_42f892_idx')],
            },
        ),
    ]
